apiVersion: v1
kind: Pod
metadata:
  name: "kuard-config"
  namespace: default
  labels:
    app: "kuard-config"
spec:
  containers:
  - name: kuard-config
    image: "gcr.io/kuar-demo/kuard-amd64:blue"
    command:
      - "/kuard"
      - "${EXTRA_PARAM}"
    env:
    - name: ANOTHER_PARAM
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: another-param
    - name: EXTRA_PARAM
      valueFrom:
        configMapKeyRef:
          name:  my-config
          key: extra-param
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name:  my-config
  restartPolicy: Never