apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-fast-strage
  namespace: default
  labels:
    app: nginx-fast-strage
spec:
  selector:
    matchLabels:
      app: nginx-fast-strage
  template:
    metadata:
      labels:
        app: nginx-fast-strage
    spec:
      nodeSelector:
        ssd: "true"
      containers:
      - name: nginx-fast-strage
        image: nginx:1.10.0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      terminationGracePeriodSeconds: 30
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai