apiVersion: v1
kind: Pod
metadata:
  name: "kuard"
  namespace: default
  labels:
    app: "kuard"
spec:
  containers:
  - name: kuard
    image: "gcr.io/kuar-demo/kuard-amd64:blue"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
    ports:
    - containerPort:  8080
      name:  http
    volumeMounts:
    - name: kuard-data
      mountPath: /data
  volumes:
    - name: kuard-data
      hostPath:
        path: /data/microk8s/kuard
