apiVersion: v1
kind: Pod
metadata:
  name: "kuard"
  namespace: default
  labels:
    app: "kuard"
spec:
  containers:
  - name: kuard
    image: "gcr.io/kuar-demo/kuard-amd64:blue"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    ports:
    - containerPort:  8080
      name:  http
    volumeMounts:
    - name: kuard-data
      mountPath: /data
  volumes:
    - name: kuard-data
      hostPath:
        path: /data/microk8s/kuard
